image: debian:stretch

before_script:
  - apt-get update -qq && apt-get install -y -qq make gcc libpcre3-dev

stages:
  - build
  - test

build:
  stage: build
  script:
    - make

# Test what has been done already
test_fait:
  stage: test
  script:
    - apt-get install -y -qq jq file libmagic-dev
    # Just to be sure
    - make
    # Test a few cases, to be grown
    - DIFF=1 ./test.sh 0,1,2,3,4,5,6,11,12

test_all:
  allow_failure: true
  stage: test
  script:
    - apt-get install -y -qq jq file libmagic-dev
    # Just to be sure
    - make
    - DIFF=1 ./test.sh

# Dynamic loading of libmagic
test_dyn_magic:
  stage: test
  script:
    - apt-get install -y -qq jq file libmagic-dev
    - make
    - DIFF=1 ./test.sh $(./list_test.sh | grep -- -i | cut -d , -f 1 | tr '\n' ',' | sed 's/,$//')

# Without libmagic
test_dyn_nomagic:
  stage: test
  script:
    - apt-get install -y -qq jq file
    - make
    - DIFF=1 ./test.sh 1,2,3
