image: debian:stretch

before_script:
  - apt-get update -qq && apt-get install -y -qq libmagic-dev make gcc

stages:
  - build
  - test

build:
  stage: build
  script:
    - make

test:
  stage: test
  script:
    - apt-get install -y -qq jq
    # Just to be sure
    - make
    # Test a few cases, to be grown
    - DIFF=1 ./test.sh 0:4

# TODO Test dynamic loading of libmagic
